package gont.vlad.g1093.dp.singleton;

public class GoogleAuthentication {

	String authURL;
	String clientID;
	String clientSecret;
	String userData;

	private static GoogleAuthentication authInstance = null;

	private GoogleAuthentication(String authURL, String clientID, String clientSecret)
			throws UnsupportedOperationException {
		if (authInstance != null) {
			throw new UnsupportedOperationException("Already established a connection to the API");
		}
		System.out.println("Accesing Google Authentication API...");
		this.authURL = authURL;
		this.clientID = clientID;
		this.clientSecret = clientSecret;
		this.userData = "User email retrieved from the API";
	}

	public static synchronized GoogleAuthentication getGoogleAuthenticationInstance() {
		if (authInstance == null) {
			String authURL = "http://localhost:8081/auth/google/redirect";
			String clientID = "Client ID generated by Google API";
			String clientSecret = "Client secret generated by Google API";
			authInstance = new GoogleAuthentication(authURL, clientID, clientSecret);
		}

		return authInstance;

	}

	public String getUserData() {
		return userData;
	}

}
